version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/libs/ibm"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: increase
    ignore:
      - dependency-name: "langchain-core"
      - dependency-name: "langchain"
      - dependency-name: "langchain-classic"
      - dependency-name: "langchain-text-splitters"
      - dependency-name: "langchain-tests"
      - dependency-name: "langchain-model-profiles"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "uv"
    directory: "/libs/langchain-db2"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: increase
    ignore:
      - dependency-name: "langchain-core"
      - dependency-name: "langchain"
      - dependency-name: "langchain-classic"
      - dependency-name: "langchain-text-splitters"
      - dependency-name: "langchain-tests"
      - dependency-name: "langchain-model-profiles"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"
