name: Tokens available check

on:
  workflow_dispatch:
    inputs:
      working-directory:
        required: true
        type: string
        default: 'libs/ibm'
      fork:
        required: true
        type: string
        default: 'langchain-ai'
        description: "Which fork to run this test against"
      branch:
        required: true
        type: string
        default: 'main'
        description: "Which branch to run this test against"
      python-version:
        required: false
        type: string
        default: "3.11"
        description: "Python version to use"

env:
  UV_FROZEN: "true"
  UV_NO_SYNC: "true"

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    runs-on: ubuntu-latest
    name: "Tokens available - Python ${{ inputs.python-version }}"
    steps:
      - uses: actions/checkout@v5
        with:
          repository: "${{ inputs.fork }}/langchain-ibm"
          ref: "${{ inputs.branch }}"

      - name: Set up Python ${{ inputs.python-version }} + uv
        uses: "./.github/actions/uv_setup"
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        shell: bash
        run: uv sync --group test --group test_integration

      - name: Run tokens available check
        shell: bash
        env:
          WATSONX_APIKEY: ${{ secrets.WATSONX_APIKEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
        run: |
          make token

      - name: Ensure the tests did not create any additional files
        shell: bash
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
